---
name: "Calibre"
guid: "7808f7b3-1de5-41d3-be53-afbf28c99fff"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Calibre metadata provider"
description: >
  Gets the metadata from calibre metadata.opf
category: "Metadata"
owner: "ashleydeo"
artifacts:
- "Jellyfin.Plugin.Calibre.dll"
changelog: >
  - Initial release
