---
name: "Calibre"
guid: "7808f7b3-1de5-41d3-be53-afbf28c99fff"
imageUrl: https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-calibre.png
version: "3.0.0"
targetAbi: "12.0.0.0"
framework: "net10.0"
owner: "ashleydeo"
overview: "Calibre metadata provider"
description: >
  Gets the metadata from calibre metadata.opf
category: "Books"
artifacts:
  - "Jellyfin.Plugin.Calibre.dll"
changelog: >
  - Updated for 12.0
